In [29]:
#using numpy
from numpy import *

In [30]:
#using Pandas
import os
import pandas as pd
import numpy as no
os.chdir("C:\\Users\\caccess\\Downloads")

In [31]:
!type ccp_current_csv.csv

STREET,QUADRANT,FROMINTERSECTION,TOINTERSECTION,NOOFBLOCKS,WORKDESCRIPTION,YEARBUDGETED,PERCENTCOMPLETED,STATUS,MILES,WARD,FUNCTIONALCLASS,ESTIMATEDSTARTDATE,ESTIMATEDCOMPLETIONDATE,ACTUALCOMPLETIONDATE,REMARKS,XCOORD,YCOORD,LATITUDE,LONGITUDE,PROJECTNOTE,PROJECTNAME,PROJECTMGR,PROJECTID,TEAMREP,EMAIL,CONTACTPHONE
13th St,NW,Kennedy St,Longfellow St,1,Pavement Resurface/restoration,2004,100,Completed,0.07,4,MINOR ARTERIAL,4/4/2005 0:00,8/1/2005 0:00,8/1/2005 0:00,WASA Lead Location FY-05,397426.2485,143205.1198,38.95674729,-77.02969433,,FedAid,Paul Stephenson,5834,O. Hill,N/A,202-671-4591
S St,NW,North Capitol St,3rd St,3,Regular Cover,1999,100,Completed,0.33,5,LOCAL,3/31/2004 0:00,,8/1/2005 0:00,2 Year CIP 2001 - 2003,398923.6065,138468.9026,38.91408514,-77.01241132,,,,2467,,,
Rhode Island Ave,NE,Brentwood Rd (W),Brentwood Rd (M),1,Pavement Resurface/restoration,2004,100,Completed,0.09,5,PRINCIPAL ARTERIAL,7/1/2005 0:00,8/5/2005 0:00,8/3/2005 0:00,,401108.1146,139574.1066,38.92404114,

In [32]:
# reading data in table format
data = pd.read_table("ccp_current_csv.csv", sep=',', header=None)
data

0         1                           2   \
0                STREET  QUADRANT            FROMINTERSECTION   
1               13th St        NW                  Kennedy St   
2                  S St        NW            North Capitol St   
3      Rhode Island Ave        NE            Brentwood Rd (W)   
4               Mill Rd        NW                     27th St   
5      Rhode Island Ave        NE            Brentwood Rd (M)   
6             Mellon St        SE                      5th St   
7          Nebraska Ave        NW              Northampton St   
8           Military Rd        NW                     30th St   
9          Nebraska Ave        NW                   Oliver St   
10              16th St        NW                  Alaska Ave   
11         Shoemaker St        NW                 Linnean Ave   
12         Underwood St        NW             Piney Branch Rd   
13             Elder St        NW                      7th St   
14              26th St        NW              Northampton St   
15               4th St        NW              Madison St (N)   
16         Underwood Pl        NW            North Capitol St   
17              20th St        NW                 Columbia Rd   
18          Quintana Pl        NE                      3rd St   
19         Tuckerman St        NE                  Kansas Ave   
20              Eads St        NE                     45th St   
21               4th St        SE                  Newcomb St   
22              Belt Rd        NW                  Jenifer St   
23            Oneida St        NE           New Hampshire Ave   
24      Carrollsburg Pl        SW                        O St   
25              23rd St        NW          Washington Cir (N)   
26           Kanawha St        NW                    Utah Ave   
27      Piney Branch Rd        NW                Underwood St   
28              30th St        NW               Stephenson Pl   
29              32nd St        NW                 Woodland Dr   
..                  ...       ...                         ...   
436      New Jersey Ave        NW                        F St   
437             15th St        NE                     Ames Pl   
438     East Capitol St        BN                        C St   
439         Randolph St        NE                     25th Pl   
440    South Dakota Ave        NE                Delafield St   
441          Wheeler Rd        SE                 Congress St   
442      New Jersey Ave        NW                        H St   
443     Mount Olivet Rd        NE               Brentwood Pky   
444              Oak St        NW                     16th St   
445        Michigan Ave        NE                     14th St   
446                C St        NE                     20th St   
447        Virginia Ave        SE                  6th St (S)   
448              Oak St        NW                Brown St (N)   
449         Florida Ave        NE                New York Ave   
450  North Carolina Ave        NE         East Capitol St (E)   
451            Elder St        NW                      8th St   
452          Benning Rd        SE                        G St   
453           School St        SW                      4th St   
454             18th St        NW                        M St   
455       Longfellow St        NW                     16th St   
456             10th St        NW                        M St   
457          Woodley Rd        NW             Connecticut Ave   
458          Woodley Rd        NW           Cathedral Ave (E)   
459              3rd St        SW            Independence Ave   
460             16th St        NW                 Primrose Rd   
461          Woodley Rd        NW                  Woodley Pl   
462         Western Ave        NW         Chevy Chase Cir (E)   
463             49th St        NW                   Fulton St   
464       Quackenbos St        NE           New Hampshire Ave   
465    North Capitol St        BN  Hawaii Ave  Rock Cree

In [33]:
data = genfromtxt('ccp_current_csv.csv', delimiter=',', dtype=None,usecols=arange(0,27))
       

In [35]:
type(data)

numpy.ndarray

In [36]:
data.shape

(466L, 27L)

shape gives the matrix dimensions(number of rows,number of columns)


The suffix L returned by the shape property has nothing to do with the data you can put in your arrays and you should not be concerned with it. L denotes the long Python type used to represent integers of unbounded width . It doesn't make much sense to represent a small integer  as long, but some code does it anyway for consistency with the same API returning a larger integer. 

In [37]:
data.size

12582

size gives total number of elemnts in the array

In [38]:
type(data)

numpy.ndarray

In [39]:
data.dtype

dtype('S198')

In [40]:
data

array([['STREET', 'QUADRANT', 'FROMINTERSECTION', ..., 'TEAMREP', 'EMAIL',
        'CONTACTPHONE'],
       ['13th St', 'NW', 'Kennedy St', ..., 'O. Hill', 'N/A',
        '202-671-4591'],
       ['S St', 'NW', 'North Capitol St', ..., '', '', ''],
       ..., 
       ['49th St', 'NW', 'Fulton St', ..., 'Deguzman', '', '202-671-4591'],
       ['Quackenbos St', 'NE', 'New Hampshire Ave', ..., '', '', ''],
       ['North Capitol St', 'BN', 'Hawaii Ave  Rock Creek Chu', ...,
        'Stanley Freeman', 'Stanley.Freeman@dc.gov', '202-234-1458']], 
      dtype='|S198')

In [41]:
h = len(data[1])
w = len(data)
top_left =  [data[i][:h / 2] for i in range(w / 2)]
top_right = [data[i][h / 2:] for i in range(w / 2)]
bot_left =  [data[i][:h / 2] for i in range(w / 2, w)]
bot_right = [data[i][h / 2:] for i in range(w / 2, w)]

In [42]:
Q1=array([top_left])
Q1.shape[1]
#these are the number of rows in the first QUADRANT

233L

In [43]:
Q1=array([top_left])
Q1.shape[2]
#these are the number of columns in the first QUADRANT

13L

In [44]:
Q2=array([top_right])
Q2.shape[1]
#these are the number of rows in the second QUADRANT

233L

In [45]:
Q2=array([top_right])
Q2.shape[2]
#these are the number of columns in the second QUADRANT

14L

In [46]:
Q3=array([bot_left])
Q3.shape[1]
#these are the number of rows in the third QUADRANT

233L

In [47]:
Q3=array([bot_left])
Q3.shape[2]
#these are the number of columns in the third QUADRANT

13L

In [48]:
Q4=array([bot_right])
Q4.shape[1]
#these are the number of rows in the fourth QUADRANT

233L

In [49]:
Q4=array([bot_right])
Q4.shape[2]
#these are the number of columns in the fourth QUADRANT

14L

In [50]:
a= array([1,2,3,4],dtype=float)
b = array([5,6,7,8],dtype=float)

In [51]:
a.dtype
b.dtype

dtype('float64')

In [52]:
a+b

array([  6.,   8.,  10.,  12.])

In [53]:
add(a,b)

array([  6.,   8.,  10.,  12.])

In [54]:
a-b


array([-4., -4., -4., -4.])

In [55]:
subtract(a,b)

array([-4., -4., -4., -4.])

In [56]:
a*b


array([  5.,  12.,  21.,  32.])

In [57]:
multiply(a,b)

array([  5.,  12.,  21.,  32.])

In [58]:
a/b

array([ 0.2       ,  0.33333333,  0.42857143,  0.5       ])

In [59]:
divide(a,b)

array([ 0.2       ,  0.33333333,  0.42857143,  0.5       ])

In [60]:
a%b

array([ 1.,  2.,  3.,  4.])

In [61]:
mod(a,b)

array([ 1.,  2.,  3.,  4.])

In [62]:
a**b

array([  1.00000000e+00,   6.40000000e+01,   2.18700000e+03,
         6.55360000e+04])

In [63]:
power(a,b)

array([  1.00000000e+00,   6.40000000e+01,   2.18700000e+03,
         6.55360000e+04])

In [68]:
#using numpy
with open("tobaco.csv",'r') as f, open("updated_tobaco.csv",'w') as f1:
  next(f) 
  for line in f:
          f1.write(line)

In [69]:
given= genfromtxt('updated_tobaco.csv', delimiter=',', dtype=float,usecols=arange(0,14))

In [70]:
given.shape

(221L, 14L)

In [71]:
given.dtype

dtype('float64')

In [72]:
type(given)

numpy.ndarray

In [73]:
given.size

3094

In [74]:
#finding minimum and maximum in total percaptia income over all years
y=(given[:,10])
z=(y[1:-1])
print("minimum total import  is:", min(z))
print("maximum total maximum is:", max(z))

('minimum total import  is:', 3177008.0)
('maximum total maximum is:', 441000000000.0)


In [75]:
#using pandas
import os
import pandas as pd
os.chdir("C:\Users\caccess\Downloads")

In [76]:
!type tobaco.csv

Year,LocationAbbrev,LocationDesc,Population,Topic,Measure,Submeasure,Data Value Unit,Domestic,Imports,Total,Domestic Per Capita,Imports Per Capita,Total Per Capita
2000,US,National,209786736,Combustible Tobacco,All Combustibles,Total Combustible Tobacco,Cigarette Equivalents,4.37E+11,13570647662,4.51E+11,2084,65,2148
2001,US,National,212345162,Combustible Tobacco,All Combustibles,Total Combustible Tobacco,Cigarette Equivalents,4.24E+11,16245487123,4.41E+11,1999,77,2075
2002,US,National,214754648,Combustible Tobacco,All Combustibles,Total Combustible Tobacco,Cigarette Equivalents,4.08E+11,22459975923,4.31E+11,1901,105,2006
2003,US,National,217068101,Combustible Tobacco,All Combustibles,Total Combustible Tobacco,Cigarette Equivalents,3.91E+11,24733051892,4.16E+11,1802,114,1916
2004,US,National,219552929,Combustible Tobacco,All Combustibles,Total Combustible Tobacco,Cigarette Equivalents,3.90E+11,24254733538,4.14E+11,1777,110,1888
2005,US,National,222003984,Combustible Tobacco,All Combust

In [195]:
tobaco = pd.read_csv("tobaco.csv", index_col='Year')

In [196]:
tobaco = tobaco.rename(columns={'Data Value Unit': 'type'})
tobaco = tobaco.rename(columns={'Total Per Capita': 'tpc'})

In [197]:
pd.Series(tobaco.Topic).value_counts()


Combustible Tobacco       187
Noncombustible Tobacco     34
Name: Topic, dtype: int64

In [198]:
pd.Series(tobaco.Measure).value_counts()


Loose Tobacco        102
Cigars                51
Smokeless Tobacco     34
All Combustibles      17
Cigarettes            17
Name: Measure, dtype: int64

In [199]:
pd.Series(tobaco.Submeasure).value_counts()

Total Loose Tobacco          34
Roll-Your-Own Tobacco        34
Pipe Tobacco                 34
Total Cigars                 17
Chewing Tobacco              17
Total Combustible Tobacco    17
Large Cigars                 17
Snuff                        17
Cigarette Removals           17
Small Cigars                 17
Name: Submeasure, dtype: int64

In [200]:
 tobaco.set_index(['Measure'])


LocationAbbrev LocationDesc  Population  \
Measure                                                     
All Combustibles              US     National   209786736   
All Combustibles              US     National   212345162   
All Combustibles              US     National   214754648   
All Combustibles              US     National   217068101   
All Combustibles              US     National   219552929   
All Combustibles              US     National   222003984   
All Combustibles              US     National   224583123   
All Combustibles              US     National   227239768   
All Combustibles              US     National   229945137   
All Combustibles              US     National   232458335   
All Combustibles              US     National   235153929   
All Combustibles              US     National   237657645   
All Combustibles              US     National   240185952   
All Combustibles              US     National   242542967   
All Combustibles              US     National   245273438   
All Combustibles              US     National   247773709   
Cigarettes                    US     National   209786736   
Cigarettes                    US     National   212345162   
Cigarettes                    US     National   214754648   
Cigarettes                    US     National   217068101   
Cigarettes                    US     National   219552929   
Cigarettes                    US     National   222003984   
Cigarettes                    US     National   224583123   
Cigarettes                    US     National   227239768   
Cigarettes                    US     National   229945137   
Cigarettes                    US     National   232458335   
Cigarettes                    US     National   235153929   
Cigarettes                    US     National   237657645   
Cigarettes                    US     National   240185952   
Cigarettes                    US     National   242542967   
...                          ...          ...         ...   
Smokeless Tobacco             US     National   245273438   
Smokeless Tobacco             US     National   247773709   
Smokeless Tobacco             US     National   209786736   
Smokeless Tobacco             US     National   212345162   
Smokeless Tobacco             US     National   214754648   
Smokeless Tobacco             US     National   217068101   
Smokeless Tobacco             US     National   219552929   
Smokeless Tobacco             US     National   224583123   
Smokeless Tobacco             US     National   227239768   
Smokeless Tobacco             US     National   229945137   
Smokeless Tobacco             US     National   232458335   
Smokeless Tobacco             US     National   235153929   
Smokeless Tobacco             US     National   237657645   
Smokeless Tobacco             US     National   240185952   
Smokeless Tobacco             US     National   242542967   
Smokeless Tobacco             US     National   245273438   
Smokeless Tobacco             US     National   247773709   
All Combustibles              US     National   249485228   
Cigarettes                    US     National   249485228   
Cigars                        US     National   249485228   
Cigars                        US     National   249485228   
Cigars                        US     National   249485228   
Loose Tobacco                 US     National   249485228   
Loose Tobacco                 US     National   249485228   
Loose Tobacco                 US     National   249485228   
Loose Tobacco                 US     National   249485228   
Loose Tobacco                 US     National   249485228   
Loose Tobacco                 US     National   249485228   
Smokeless Tobacco             US     National   249485228   
Smokeless Tobacco             US     National   249485228   

                                    Topic                 Submeasure  \
Measure                                                                
All Combustibles      Combusti

In [201]:
 tobaco.set_index(['Submeasure'])

LocationAbbrev LocationDesc  Population  \
Submeasure                                                          
Total Combustible Tobacco             US     National   209786736   
Total Combustible Tobacco             US     National   212345162   
Total Combustible Tobacco             US     National   214754648   
Total Combustible Tobacco             US     National   217068101   
Total Combustible Tobacco             US     National   219552929   
Total Combustible Tobacco             US     National   222003984   
Total Combustible Tobacco             US     National   224583123   
Total Combustible Tobacco             US     National   227239768   
Total Combustible Tobacco             US     National   229945137   
Total Combustible Tobacco             US     National   232458335   
Total Combustible Tobacco             US     National   235153929   
Total Combustible Tobacco             US     National   237657645   
Total Combustible Tobacco             US     National   240185952   
Total Combustible Tobacco             US     National   242542967   
Total Combustible Tobacco             US     National   245273438   
Total Combustible Tobacco             US     National   247773709   
Cigarette Removals                    US     National   209786736   
Cigarette Removals                    US     National   212345162   
Cigarette Removals                    US     National   214754648   
Cigarette Removals                    US     National   217068101   
Cigarette Removals                    US     National   219552929   
Cigarette Removals                    US     National   222003984   
Cigarette Removals                    US     National   224583123   
Cigarette Removals                    US     National   227239768   
Cigarette Removals                    US     National   229945137   
Cigarette Removals                    US     National   232458335   
Cigarette Removals                    US     National   235153929   
Cigarette Removals                    US     National   237657645   
Cigarette Removals                    US     National   240185952   
Cigarette Removals                    US     National   242542967   
...                                  ...          ...         ...   
Chewing Tobacco                       US     National   245273438   
Chewing Tobacco                       US     National   247773709   
Snuff                                 US     National   209786736   
Snuff                                 US     National   212345162   
Snuff                                 US     National   214754648   
Snuff                                 US     National   217068101   
Snuff                                 US     National   219552929   
Snuff                                 US     National   224583123   
Snuff                                 US     National   227239768   
Snuff                                 US     National   229945137   
Snuff                                 US     National   232458335   
Snuff                                 US     National   235153929   
Snuff                                 US     National   237657645   
Snuff                                 US     National   240185952   
Snuff                                 US     National   242542967   
Snuff                                 US     National   245273438   
Snuff                                 US     National   247773709   
Total Combustible Tobacco             US     National   249485228   
Cigarette Removals                    US     National   249485228   
Large Cigars                          US     National   249485228   
Small Cigars                          US     National   249485228   
Total Cigars                          US     National   249485228   
Pipe Tobacco                          US     National   249485228   
Pipe Tobacco                          US     National   249485228   
Roll-Your-Own Tobacco                 US     National   249485228   
Roll-Your-Own Tobacco   

In [202]:
tobaco.mean()

Population             2.298712e+08
Domestic               5.543751e+10
Imports                2.866887e+09
Total                  5.833213e+10
Domestic Per Capita    2.436380e+02
Imports Per Capita     1.251131e+01
tpc                    2.561719e+02
dtype: float64

In [203]:
tobaco.Measure.describe()

count               221
unique                5
top       Loose Tobacco
freq                102
Name: Measure, dtype: object

In [204]:
tobaco.Submeasure.describe()

count                     221
unique                     10
top       Total Loose Tobacco
freq                       34
Name: Submeasure, dtype: object

In [205]:
tobaco.type.describe()

count        221
unique         4
top       Pounds
freq          85
Name: type, dtype: object

In [206]:
tobaco.sum()

LocationAbbrev         USUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUSUS...
LocationDesc           NationalNationalNationalNationalNationalNation...
Population                                                   50801540283
Topic                  Combustible TobaccoCombustible TobaccoCombusti...
Measure                All CombustiblesAll CombustiblesAll Combustibl...
Submeasure             Total Combustible TobaccoTotal Combustible Tob...
type                   Cigarette EquivalentsCigarette EquivalentsCiga...
Domestic                                                     1.22517e+13
Imports                                                     633582116573
Total                                                        1.28914e+13
Domestic Per Capita                                                53844
Imports Per Capita                                                  2765
tpc                                                                56614
dtype: object

# Real analysis starts here,I am analysing the "Total(domestic+imports)" and "total Per captia" for different tobaco usage over all the 17 years.

In [241]:
tobaco1=tobaco[(tobaco.Topic == 'Combustible Tobacco') & (tobaco.Measure == 'All Combustibles') & (tobaco.Submeasure  == 'Total Combustible Tobacco') & (tobaco.type  == 'Cigarette Equivalents')]
tobaco11 = tobaco1[['Total','tpc']]
print(tobaco11)
Total_sum1=tobaco11['Total'].sum()
Total_sum1tpc_sum1=tobaco11['tpc'].sum()
Total_sum1

             Total   tpc
Year                    
2000  4.510000e+11  2148
2001  4.410000e+11  2075
2002  4.310000e+11  2006
2003  4.160000e+11  1916
2004  4.140000e+11  1888
2005  4.010000e+11  1807
2006  4.010000e+11  1787
2007  3.840000e+11  1690
2008  3.710000e+11  1615
2009  3.420000e+11  1472
2010  3.290000e+11  1400
2011  3.270000e+11  1374
2012  3.220000e+11  1342
2013  3.100000e+11  1277
2014  2.980000e+11  1216
2015  3.020000e+11  1217
2016  2.910000e+11  1164


6231000000000.0

In [239]:
tpc_sum1=tobaco11['tpc'].sum()
tpc_sum1

27394L

In [218]:
tobaco2=tobaco[(tobaco.Topic == 'Combustible Tobacco') & (tobaco.Measure == 'Cigarettes') & (tobaco.Submeasure  == 'Cigarette Removals') & (tobaco.type  == 'Cigarettes')]
tobaco22 = tobaco2[['Total','tpc']]
print(tobaco22)
Total_sum2=tobaco22['Total'].sum()

             Total   tpc
Year                    
2000  4.360000e+11  2076
2001  4.270000e+11  2010
2002  4.160000e+11  1936
2003  4.000000e+11  1844
2004  3.980000e+11  1811
2005  3.810000e+11  1717
2006  3.810000e+11  1695
2007  3.620000e+11  1591
2008  3.460000e+11  1507
2009  3.180000e+11  1367
2010  3.000000e+11  1278
2011  2.930000e+11  1232
2012  2.870000e+11  1196
2013  2.740000e+11  1129
2014  2.630000e+11  1071
2015  2.680000e+11  1081
2016  2.570000e+11  1032


In [242]:
tpc_sum2=tobaco22['tpc'].sum()
tpc_sum2

25573L

In [219]:
tobaco3=tobaco[(tobaco.Topic == 'Combustible Tobacco') & (tobaco.Measure == 'Loose Tobacco') & (tobaco.Submeasure  == 'Pipe Tobacco') & (tobaco.type  == 'Cigarette Equivalents')  ]
tobaco33 = tobaco3[['Total','tpc']]
print(tobaco33)
Total_sum3=tobaco33['Total'].sum()

             Total  tpc
Year                   
2000  2.999419e+09   14
2001  2.914667e+09   14
2002  2.757070e+09   13
2003  2.389312e+09   11
2004  2.313500e+09   11
2005  2.422650e+09   11
2006  2.321892e+09   10
2007  2.462587e+09   11
2008  2.585503e+09   11
2009  6.255704e+09   27
2010  1.235135e+10   53
2011  1.745933e+10   73
2012  1.918256e+10   80
2013  2.079904e+10   86
2014  2.022622e+10   82
2015  1.986726e+10   80
2016  1.948411e+10   78


In [244]:
tpc_sum3=tobaco33['tpc'].sum()
tpc_sum3tpc_sum1=tobaco11['tpc'].sum()
tpc_sum1

27394L

In [245]:
tobaco4=tobaco[(tobaco.Topic == 'Combustible Tobacco') & (tobaco.Measure == 'Loose Tobacco') & (tobaco.Submeasure  == 'Pipe Tobacco') & (tobaco.type  == 'Pounds')]
tobaco44 = tobaco4[['Total','tpc']]
print(tobaco44)
Total_sum4=tobaco44['Total'].sum()

           Total  tpc
Year                 
2000   6092570.0    0
2001   5920417.0    0
2002   5600299.0    0
2003   4853291.0    0
2004   4699297.0    0
2005   4921008.0    0
2006   4716343.0    0
2007   5002130.0    0
2008   5251802.0    0
2009  12706899.0    0
2010  25088678.0    0
2011  35464274.0    0
2012  38964565.0    0
2013  42248055.0    0
2014  41084509.0    0
2015  40355367.0    0
2016  39577107.0    0


In [246]:
tpc_sum4=tobaco44['tpc'].sum()
tpc_sum4

0L

In [247]:
tobaco5=tobaco[(tobaco.Topic == 'Combustible Tobacco') & (tobaco.Measure == 'Loose Tobacco') & (tobaco.Submeasure  == 'Roll-Your-Own Tobacco') & (tobaco.type  == 'Cigarette Equivalents')  ]
tobaco55 = tobaco5[['Total','tpc']]
print(tobaco55)
Total_sum5=tobaco55['Total'].sum()

             Total  tpc
Year                   
2000  5.994599e+09   29
2001  4.714089e+09   22
2002  5.736680e+09   27
2003  6.206594e+09   29
2004  6.600411e+09   30
2005  8.614158e+09   39
2006  8.593555e+09   38
2007  9.325676e+09   41
2008  1.072149e+10   47
2009  6.005709e+09   26
2010  3.167671e+09   13
2011  2.621590e+09   11
2012  2.239867e+09    9
2013  1.897622e+09    8
2014  1.593844e+09    6
2015  1.804211e+09    7
2016  1.564065e+09    6


In [248]:
tpc_sum5=tobaco55['tpc'].sum()
tpc_sum5

388L

In [237]:
tobaco6=tobaco[(tobaco.Topic == 'Combustible Tobacco') & (tobaco.Measure == 'Loose Tobacco') & (tobaco.Submeasure  == 'Roll-Your-Own Tobacco') & (tobaco.type  == 'Pounds')  ]
tobaco66 = tobaco6[['Total','tpc']]
print(tobaco66)
Total_sum6=tobaco66['Total'].sum()
Total_sum6

           Total  tpc
Year                 
2000  12176530.0    0
2001   9575493.0    0
2002  11652631.0    0
2003  12607145.0    0
2004  13407084.0    0
2005  17497508.0    0
2006  17455658.0    0
2007  18942779.0    0
2008  21778018.0    0
2009  12199096.0    0
2010   6434332.0    0
2011   5325105.0    0
2012   4549729.0    0
2013   3854544.0    0
2014   3237495.0    0
2015   3664804.0    0
2016   3177008.0    0


177534959.0

In [249]:
tpc_sum6=tobaco66['tpc'].sum()
tpc_sum6

0L

In [236]:
tobaco7=tobaco[(tobaco.Topic == 'Combustible Tobacco') & (tobaco.Measure == 'Loose Tobacco') & (tobaco.Submeasure  == 'Total Loose Tobacco') & (tobaco.type  == 'Cigarette Equivalents')  ]
tobaco77 = tobaco7[['Total','tpc']]
print(tobaco77)
Total_sum7=tobaco77['Total'].sum()
Total_sum7

             Total  tpc
Year                   
2000  8.994018e+09   43
2001  7.628756e+09   36
2002  8.493750e+09   40
2003  8.595907e+09   40
2004  8.913911e+09   41
2005  1.103681e+10   50
2006  1.091545e+10   49
2007  1.178826e+10   52
2008  1.330699e+10   58
2009  1.226141e+10   53
2010  1.551902e+10   66
2011  2.008093e+10   84
2012  2.142242e+10   89
2013  2.269666e+10   94
2014  2.182006e+10   89
2015  2.167147e+10   87
2016  2.104818e+10   84


246194003693.0

In [250]:
tpc_sum7=tobaco77['tpc'].sum()
tpc_sum7

1055L

In [235]:
tobaco8=tobaco[(tobaco.Topic == 'Noncombustible Tobacco') & (tobaco.Measure == 'Smokeless Tobacco') & (tobaco.Submeasure  == 'Chewing Tobacco') & (tobaco.type  == 'Pounds')]
tobaco88 = tobaco8[['Total','tpc']]
print(tobaco88)
Total_sum8=tobaco88['Total'].sum()
Total_sum8

           Total  tpc
Year                 
2000  45594121.0    0
2001  49499686.0    0
2002  47310983.0    0
2003  46080466.0    0
2004  43149090.0    0
2005  39199192.0    0
2006  39097823.0    0
2007  35304039.0    0
2008  33445940.0    0
2009  30425086.0    0
2010  27614984.0    0
2011  24800532.0    0
2012  24145994.0    0
2013  22433701.0    0
2014  21965411.0    0
2015  20211121.0    0
2016  20005929.0    0


570284098.0

In [251]:
tpc_sum8=tobaco88['tpc'].sum()
tpc_sum8

0L

In [234]:
tobaco9=tobaco[(tobaco.Topic == 'Noncombustible Tobacco') & (tobaco.Measure == 'Smokeless Tobacco') & (tobaco.Submeasure  == 'Snuff') & (tobaco.type  == 'Pounds')]
tobaco99 = tobaco9[['Total','tpc']]
print(tobaco99)
Total_sum9=tobaco99['Total'].sum()
Total_sum9

            Total  tpc
Year                  
2005   80252594.0    0
2000   66152359.0    0
2001   69816481.0    0
2002   71252759.0    0
2003   74709084.0    0
2004   78000270.0    0
2006   86640004.0    0
2007   88367787.0    0
2008   94818661.0    0
2009   95053755.0    0
2010   99912177.0    0
2011  103561975.0    0
2012  108205345.0    0
2013  113006625.0    0
2014  114367744.0    0
2015  117571820.0    0
2016  119084041.0    0


1580773481.0

In [252]:
tpc_sum9=tobaco99['tpc'].sum()
tpc_sum9

0L

In [231]:
l=[Total_sum1,Total_sum2,Total_sum3,Total_sum4,Total_sum5,Total_sum6,Total_sum7,Total_sum8,Total_sum9]
max (l)

6231000000000.0

By this analysis we can draw that Topic of 'Combustible Tobacco' & Measure of 'All Combustibles' & Submeasure  of 'Total Combustible Tobacco' & type  of 'Cigarette Equivalents'are the most consumed product over the years.

In [233]:
l=[Total_sum1,Total_sum2,Total_sum3,Total_sum4,Total_sum5,Total_sum6,Total_sum7,Total_sum8,Total_sum9]
min (l)

177534959.0

By this analysis we can draw that Topic of 'Combustible Tobacco' & Measure of 'Loose Tobacco' & Submeasure  of 'Roll-Your-Own Tobacco' & type  of 'Pounds'are the least consumed product over the years.

In [253]:
m=[tpc_sum1,tpc_sum2,tpc_sum3,tpc_sum4,tpc_sum5,tpc_sum6,tpc_sum7,tpc_sum8,tpc_sum9]
max (m)

27394L

By this analysis we can draw that Topic of 'Combustible Tobacco' & Measure of 'Loose Tobacco' & Submeasure  of 'Pipe Tobacco' & type  of 'Cigarette Equivalents' generate the heighest Total percaptia income over the years.

In [255]:
m=[tpc_sum1,tpc_sum2,tpc_sum3,tpc_sum4,tpc_sum5,tpc_sum6,tpc_sum7,tpc_sum8,tpc_sum9]
min(m)

0L

By this analysis we can draw that Topic of 'Combustible Tobacco' & Measure of 'Loose Tobacco' & Submeasure  of 'Pipe Tobacco' & type  of 'Pounds' generate the least Total percaptia income over the years.

By this analysis we can draw that Topic of 'Combustible Tobacco' & Measure of 'Loose Tobacco' & Submeasure  of 'Roll-Your-Own Tobacco' & type  of 'Pounds' generate the least Total percaptia income over the years.

By this analysis we can draw that Topic of 'Combustible Tobacco' & Measure of 'Smokeless Tobacco' & Submeasure  of 'Chewing Tobacco' & type  of 'Pounds' generate the least Total percaptia income over the years.

By this analysis we can draw that Topic of 'NonCombustible Tobacco' & Measure of 'Smokeless Tobacco' & Submeasure  of 'Snuff' & type  of 'Pounds' generate the least Total percaptia income over the years.

In [257]:
#total(domestic and imports) is sorted in order over the years
sorted ([Total_sum1,Total_sum2,Total_sum3,Total_sum4,Total_sum5,Total_sum6,Total_sum7,Total_sum8,Total_sum9])

[177534959.0,
 322546611.0,
 570284098.0,
 1580773481.0,
 87401825972.0,
 158792177722.0,
 246194003693.0,
 5807000000000.0,
 6231000000000.0]

In [258]:
#total per captia income is sorted in order over the years
sorted([tpc_sum1,tpc_sum2,tpc_sum3,tpc_sum4,tpc_sum5,tpc_sum6,tpc_sum7,tpc_sum8,tpc_sum9])

[0L, 0L, 0L, 0L, 388L, 665L, 1055L, 25573L, 27394L]